package com.tekwill.learning.trivia;

public class Questions {
    public static final String LEVEL_1_QUESTION_1 = "Which is the closest star to Earth?";
    public static final String LEVEL_1_QUESTION_1_ANSWER_1 = "Sirius";
    public static final String LEVEL_1_QUESTION_1_ANSWER_2 = "Vega";
    public static final String LEVEL_1_QUESTION_1_ANSWER_3 = "Sun";
    public static final String LEVEL_1_QUESTION_1_ANSWER_4 = "Rigel";
    public static final int LEVEL_1_QUESTION_3_SCORE = 100;
    public static final String LEVEL_1_QUESTION_2 = "How many planets is the sun surrounded by?";
    public static final String LEVEL_1_QUESTION_2_ANSWER_1 = "4";
    public static final String LEVEL_1_QUESTION_2_ANSWER_2 = "6";
    public static final String LEVEL_1_QUESTION_2_ANSWER_3 = "1";
    public static final String LEVEL_1_QUESTION_2_ANSWER_4 = "9";
    public static final int LEVEL_1_QUESTION_4_SCORE = 100;
    public static final String LEVEL_2_QUESTION_1 = "What is the largest planet in the solar system?";
    public static final String LEVEL_2_QUESTION_1_ANSWER_1 = "Jupiter";
    public static final String LEVEL_2_QUESTION_1_ANSWER_2 = "Saturn";
    public static final String LEVEL_2_QUESTION_1_ANSWER_3 = "Pluto";
    public static final String LEVEL_2_QUESTION_1_ANSWER_4 = "Neptun";
    public static final int LEVEL_2_QUESTION_1_SCORE = 100;
    public static final String LEVEL_2_QUESTION_2 = "What was the name of the first man to reach space?";
    public static final String LEVEL_2_QUESTION_2_ANSWER_1 = "Neil Armstrong";
    public static final String LEVEL_2_QUESTION_2_ANSWER_2 = "Iuri Gagarin";
    public static final String LEVEL_2_QUESTION_2_ANSWER_3 = "Valentina Tereskova";
    public static final String LEVEL_2_QUESTION_2_ANSWER_4 = "Tom Cruise";
    public static final int LEVEL_2_QUESTION_2_SCORE = 100;
    public static final String LEVEL_3_QUESTION_1 = "What's the name of the first woman to reach space?";
    public static final String LEVEL_3_QUESTION_1_ANSWER_1 = "Angelina Jolie";
    public static final String LEVEL_3_QUESTION_1_ANSWER_2 = "Natsha Gagarin";
    public static final String LEVEL_3_QUESTION_1_ANSWER_3 = "Valentina Tereskova";
    public static final String LEVEL_3_QUESTION_1_ANSWER_4 = "Paris Hilton";
    public static final int LEVEL_3_QUESTION_3_SCORE = 100;
    public static final String LEVEL_3_QUESTION_2 = "What is the smallest planet?";
    public static final String LEVEL_3_QUESTION_2_ANSWER_1 = "Mercur";
    public static final String LEVEL_3_QUESTION_2_ANSWER_2 = "Marte";
    public static final String LEVEL_3_QUESTION_2_ANSWER_3 = "Venus";
    public static final String LEVEL_3_QUESTION_2_ANSWER_4 = "Uranus";
    public static final int LEVEL_3_QUESTION_1_SCORE = 100;
}
